
  
  
  // hopefully this will lay the table... 


//BELOW is for the function for appearing points
let pointsAppear = 0
let pointsEl = document.getElementById('dialogue-el')
var timer3;
timer3 = setInterval(points, 1000)
function points(){
    
    pointsAppear++;
    
    if (pointsAppear ===1){clearPoints()}
    else{pointsEl.style.opacity = pointsAppear; }}


function clearPoints(){

    clearInterval(timer3)
    
}

    


//ABOVE is for the function for appearing points 

// For the randomly generated card, using its index value, we select the associated indexed image in this array; the image displays when the card is clicked. 
let cardSelect = [ 
"1.png","2.png","3.png","4.png",
"5.png","6.png","7.png","8.png",
"9.png","10.png","11.png","12.png",
"13.png","14.png","15.png","16.png",
"17.png","18.png","19.png","20.png",
"21.png","22.png","23.png","24.png",
"25.png","26.png","27.png","28.png",
"29.png","30.png","31.png","32.png",
"33.png","34.png","35.png","36.png",
"37.png","38.png","39.png","40.png",
"41.png","42.png","43.png","44.png",
"45.png","46.png","47.png","48.png",
"49.png","50.png","51.png","52.png",]
let testEl = 2
let placedCardsArray = []
// sound to play when pair found
var audio3 = new Audio("twentyonewait.mp3")
// sound for card flip
var audio4 = new Audio("cardflip.mp3")
// sound for shuffle 
var audio5 = new Audio("shuffle clip.mp3")
let audio6 = new Audio("silence.mp3")
let audio7 = new Audio("you lose.mp3")
let audio8 = new Audio("boopstart.mp3")
let flipArray = [] // will enter pairs of cards here and compare
var pair1; 
var pair2; 
let cardsPaired = []
let tableArrayIndex = []// using this to turn the picked cards back to integer numbers
let cardSuitsArray = ["clubs","diamonds","hearts","spades"]; // for available suits
let cardNumbersArray = [1,2,3,4,5,6,7,8,9,10,11,12,13]; // for available card values
let randomSuitNum = "";// variable for generated suit index
let randomSuit = "";// variable for suit name
let randomCardNum = "";// variable for generated number
let chosenCard = "" // variable for generated number and suit combined - picked card
let tableArray = []; // cards dealt to table
//let displayEl = document.getElementById('display');// picked card display
let pairsArray = [] // this array collects all found pairs
// function for card generation






// SCORES VARIABLES
let infoEl = document.getElementById("dialogue-el")
var sumbAll; // sum of scores in the array
let totalScoreArray = []
let scoreEl = document.getElementById("score")
let totalScoreEl = document.getElementById("total-scores")
let scores = 0; // scores for pairs found




// TIMER FUNCTION VARIABLES

let minuteEl = document.getElementById("minute-el");
let secondEl = document.getElementById("second-el");
minuteEl.textContent = "05";
secondEl.textContent = "00";
var secondInSeconds;
var minuteInSeconds;
var setTime;
let timer = 300;

// TIMER FUNCTION
function CountDownTimer(){
  
   
       setTime = setInterval(function() {
           timer--;
           secondInSeconds  = timer - Math.floor(timer/60)*60
           minuteInSeconds = Math.floor(timer/60)
           secondEl.textContent = secondInSeconds
           minuteEl.textContent = minuteInSeconds
      if (minuteInSeconds < 10){minuteEl.textContent = "0" + minuteInSeconds}  
             
      if (secondInSeconds < 10){secondEl.textContent = "0" + secondInSeconds}  

   

 

    if(pairsArray.length < 52 && timer === 0){clearInterval(setTime); scoreEl.textContent = "Game Over"; scoreEl.style.opacity === 1;
    minuteEl.textContent = "05";
    secondEl.textContent = "00";}
   
       }, 1000);}






// ABOVE IS THE TIMER FUNCTION... LET'S HOPE IT WORKS


// console logging for tests
function consoleLog(){ 
    console.log(paraNum)
    console.log(scores + 15)
 }

function pickCard(){
    totalScoreArray.length = 0;
   if(tableArray.length < 52){ audio8.play();
randomSuitNum = Math.floor(Math.random()*cardSuitsArray.length)//suit generated by index
randomCardNum = Math.ceil(Math.random()*cardNumbersArray.length) // card value generated
randomSuit = cardSuitsArray[randomSuitNum]// suit name picked from randomly generated card suit index
chosenCard = randomCardNum + randomSuit // variable for value and suit of card
let  actualCard = randomSuitNum + 1 + (4*(randomCardNum - 1)) //this turns the named cards into numbers from 1-52, which will be useful for picking out the card images

// condition to prevent duplicate card generation; if duplicate generated, re-run pickCard()
if(tableArray.includes(chosenCard)){pickCard();} 
else{
tableArrayIndex.push(actualCard)
tableArray.push(chosenCard) // card pushed to table

if (tableArray.length > 51){console.log(tableArray); CountDownTimer()} 
}
}
shuffleCards()

}

// this logs the array of distributed} cards (by name) and also the index number associated with each card.   
//function logArray(){if(flipArray.length <= 2)
//if (tableArrayIndex.length > 51){ playSound(); playSound();console.log(tableArrayIndex)}if(flipArray.length <= 2)
// if (tableArray.length > 51){ playSound(); playSound();console.log(tableArray)}}

//repeats pick card (random numbers) and distribute - i.e. SHUFFLE
function shuffleCards(){
if (tableArray.length < 52){ pickCard(); 
   
        // this stops the played card from activating a second time if the game hasn't started yet and you accidentally press the button
      audio5.play();
     
      // assigns a single variable to all elements the specified class
    let imgsEl = document.getElementsByClassName('cards-all')
  
    // formats all the elements into elements of an array
      var allCards = Array.from(imgsEl)
      
      // variable for starting point of count
      let cardStart = 0;
  
      // variable we assign the timer to
      var timer2
      
      timer2 = setInterval(revealCard, 15)
      function revealCard(){
          
  // this variable returns a nodelist from all elements of the class .cards-all (not sure about the card start attribute selector though)
          const cardsEl = document.querySelectorAll(".cards-all")[cardStart];
  
      cardsEl.classList.add('deal');
      
      // variable increments by 1 (from start)
      cardStart++;
      if (cardStart === allCards.length){
       completeDeal();
      cardStart = 0;}};
        
      function completeDeal(){
      clearInterval(timer2);
      //document.getElementById('start-el').style.opacity = 1; 
  
  
      // only when this array is empty can the lay card function run. It will empty on game reset, clear cards and gameover, or you win. 
  placedCardsArray.push(testEl)
  
      }}
  } 




// clearing the tableArray so we can use the shuffle again
function resetGame(){
   
   if (flipArray.length > 0){
        placedCardsArray.pop()
    
    clearInterval(setTime);
    document.getElementById('start-el').style.zIndex = 0;
    document.getElementById('start-el').style.opacity = 100;
 


  let clearPairEl = document.getElementById("card-pairs-array")
   clearPairEl.textContent = ""

    tableArray.length = 0;
    tableArrayIndex.length = 0;
    flipArray.length = 0;
    pairsArray.length = 0;
   
    // below clears the display of paired cards and returns cards 'upsidedown' to original positions - awaiting shuffle and number allocation
    let imgsEl = document.getElementsByClassName('cards-all')
    for (var i = 0; i < imgsEl.length; i++){imgsEl[i].src = "card back red.jpg"; imgsEl[i].style.opacity = 100;}
 
}}




/*
EXPERIMENTING TO ENSURE THAT NO MORE THAN 2 CARDS CAN BE REVEALED AT THE SAME TIME - AND THAT CARDS CAN BE TURNED BACK OVER IF PICKING TWO CARDS DOES NOT RESULT IN A MATCHED PAIR. 
var numEl;
if (numEl = tableArrayIndex[0]){tableArrayIndex.pop(numEl); console.log(flipArray); card#.src = card back red.jpg)} else{
 numEl = tableArrayIndex[0]
card1.src = cardSelect[numEl - 1] }
if ( flipArray.length < 3 && tableArrayIndex.length > 51 ){flipArray.push(numEl)}
*/

// firstt row of cards - row 1
function playSound(){

    audio4.play()
}

function refreshAll(){
// not using at the moment
    location.reload();
}

function pairFound(){

    
    // this hides the 'immediate' points once a card is pressed after it appeared due to a pair being found. This is because pairFound() runs if the flipArray.length is < 2 and a card is clicked. 
    document.getElementById("dialogue-el").style.opacity = 0
if (flipArray.length > 1){
    
    pair1 = Math.ceil(flipArray[0]/4)
    pair2 = Math.ceil(flipArray[1]/4)
    //console.log(pair1)
    //console.log(pair2)
    // these return the index of the picked cards (where they lie in the tablearray index). In other words, it looks at the integer value of the flipArray card, then finds the corresponding index position in the tableArrayIndex. And we give that a variable called index1 or index1.  These integer numbers are used to pick out the correct images from the cardSelect array when the associated cards derived by dividing flipArray values match. 
    let index1 = tableArrayIndex.indexOf(flipArray[0])
   // console.log(index1)
    let index2 = tableArrayIndex.indexOf(flipArray[1])
    //console.log(index2)
    let imgsEl = document.getElementsByClassName('cards-all')
    // at last, got it. the below two functions (imgsEl[index1] etc, ) uses the indexes arrived above from the indeOf method and uses them in the HTML kind of array to change the style of the cards which have the same position as the index number we got from the table array - now we can just put it into the condition for finding pairs and make them disappear if a pair is found
   
    if (pair1 === pair2){console.log("pair found"); audio3.play();
    // once a pair is found the points() function allocates points based on how much time has elapsed since the beginning of the game. 
    points()

     pairsArray.push(flipArray[0],flipArray[1]);
    imgsEl[index1].style.opacity = 0;
    imgsEl[index2].style.opacity = 0;
    flipArray.length = 0;
    
    // attempt to push images to div of paired cards

    var img2=document.createElement("img");
    img2.src= cardSelect[tableArrayIndex[index1] -1]; // image source using card image array
    var block = document.getElementById("card-pairs-array"); // setting the div as a variable
    block.appendChild(img2); // append the image to the div
    img2.style.width = "55px"; // set width of image
    img2.style.height = "80px"; // set height of image


    console.log(tableArrayIndex[index1] -1) // checking the index number matches the paired card 1 so correct card is picked
    console.log(tableArrayIndex[index2] -1) // checking the index number matches the paired card 2 so correct card is picked
    


    var img=document.createElement("img");
    img.src= cardSelect[tableArrayIndex[index2] -1];
    var block = document.getElementById("card-pairs-array");
    block.appendChild(img);
    img.style.width = "55px";
    img.style.height = "80px";

 // points system... 
   if (minuteInSeconds >= 4 ){scores = 30}
   else if (minuteInSeconds >= 3){scores = 20}
   else if   (minuteInSeconds >= 2){scores = 15}
   else {scores = 10}
   totalScoreArray.push(scores)
   console.log(totalScoreArray)
   scoreEl.textContent = scores + "!";
 
  sumbAll =  totalScoreArray.reduce((partialSum, a) => partialSum + a, 0);

  totalScoreEl.textContent = "Score: " + " " + sumbAll ;
console.log(pairsArray);
if (pairsArray.length > 51){scoreEl.textContent = "COMPLETE"; scoreEl.style.opacity = 1; scoreEl.style.fontSize = "50px"; clearInterval(setTime); timer === 0; //resetGame();

if (pairsArray.length> 51 && minuteInSeconds > 3){clearInterval(setTime); scores = 300;totalScoreArray.push(scores);
    minuteEl.textContent = "05";
    secondEl.textContent = "00";}
  else if (pairsArray.length> 51 && minuteInSeconds > 2){clearInterval(setTime); scores = 250;totalScoreArray.push(scores);
    minuteEl.textContent = "05";
    secondEl.textContent = "00";}
  else if (pairsArray.length> 51 && minuteInSeconds > 1){clearInterval(setTime); scores = 150;totalScoreArray.push(scores);
    minuteEl.textContent = "05";
    secondEl.textContent = "00";}

    

/*
  if (pairsArray.length> 51 && minuteInSeconds > 3){clearInterval(setTime); scores = 300;totalScoreArray.push(scores);
    minuteEl.textContent = "05";
    secondEl.textContent = "00";}
  else if (pairsArray.length> 51 && minuteInSeconds > 2){clearInterval(setTime); scores = 250;totalScoreArray.push(scores);
    minuteEl.textContent = "05";
    secondEl.textContent = "00";}
  else if (pairsArray.length> 51 && minuteInSeconds > 1){clearInterval(setTime); scores = 150;totalScoreArray.push(scores);
    minuteEl.textContent = "05";
    secondEl.textContent = "00";}

*/

}

}}}




 // BELOW ARE THE FUNCTIONS FOR EACH OF THE 52 CARDS

function revealOne(){
    if(tableArray.length > 51 ){
let numElOne = tableArrayIndex[0];
console.log(flipArray)
 // COPY THE BELOW to other functions and adjust as needed
if(flipArray.includes(numElOne) && numElOne === flipArray[0]){ flipArray.shift(); document.getElementById("card1").src="card back red.jpg"; playSound();} 
 else if(flipArray.includes(numElOne) && numElOne === flipArray[1]){ flipArray.pop();  document.getElementById("card1").src="card back red.jpg"; playSound();}
 else{revealCard()}
// COPY THE ABOVE function and adjust as needed

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElOne) ){flipArray.push(numElOne); card1.src = cardSelect[numElOne - 1]; playSound();}
//console.log(flipArray);
 pairFound(); 
 }}}
   



function revealTwo(){
    if(tableArray.length > 51){ 
let numElTwo = tableArrayIndex[1]

if(flipArray.includes(numElTwo) && numElTwo === flipArray[0]){ flipArray.shift(); document.getElementById("card2").src="card back red.jpg";playSound();} 
 else if(flipArray.includes(numElTwo) && numElTwo === flipArray[1]){ flipArray.pop();  document.getElementById("card2").src="card back red.jpg";playSound();}
 else{revealCard()}
 

 function revealCard(){
    if (flipArray.length < 2 && !pairsArray.includes(numElTwo) ){flipArray.push(numElTwo); card2.src = cardSelect[numElTwo - 1]; playSound();}
    //console.log(flipArray);
     pairFound(); 
     }}}




function revealThree(){
    if(tableArray.length > 51){ 
    let numElThree = tableArrayIndex[2]
    
    if(flipArray.includes(numElThree) && numElThree === flipArray[0]){ flipArray.shift(); document.getElementById("card3").src="card back red.jpg"; playSound();} 
    else if(flipArray.includes(numElThree) && numElThree === flipArray[1]){ flipArray.pop();  document.getElementById("card3").src="card back red.jpg"; playSound();}
    else{revealCard()}
   
   function revealCard(){
   if (flipArray.length < 2 && !pairsArray.includes(numElThree)){flipArray.push(numElThree); card3.src = cardSelect[numElThree - 1]; playSound();}
   //console.log(flipArray)
   pairFound()
    }}}




function revealFour(){
    if(tableArray.length > 51){ 
let numElFour = tableArrayIndex[3]

if(flipArray.includes(numElFour) && numElFour === flipArray[0]){ flipArray.shift(); document.getElementById("card4").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFour) && numElFour === flipArray[1]){ flipArray.pop();  document.getElementById("card4").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFour)){flipArray.push(numElFour); card4.src = cardSelect[numElFour - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealFive(){
    if(tableArray.length > 51){ 
let numElFive = tableArrayIndex[4]

    if(flipArray.includes(numElFive) && numElFive === flipArray[0]){ flipArray.shift(); document.getElementById("card5").src="card back red.jpg"; playSound();} 
    else if(flipArray.includes(numElFive) && numElFive === flipArray[1]){ flipArray.pop();  document.getElementById("card5").src="card back red.jpg"; playSound();}
    else{revealCard()}
   
   function revealCard(){
   if (flipArray.length < 2 && !pairsArray.includes(numElFive)){flipArray.push(numElFive); card5.src = cardSelect[numElFive - 1]; playSound();}
   //console.log(flipArray)
   pairFound()
    }}}




 function revealSix(){
    if(tableArray.length > 51){ 
let numElSix = tableArrayIndex[5]

if(flipArray.includes(numElSix) && numElSix === flipArray[0]){ flipArray.shift(); document.getElementById("card6").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElSix) && numElSix === flipArray[1]){ flipArray.pop();  document.getElementById("card6").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElSix)){flipArray.push(numElSix); card6.src = cardSelect[numElSix - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealSeven(){
    if(tableArray.length > 51){
let numElSeven = tableArrayIndex[6]

if(flipArray.includes(numElSeven) && numElSeven === flipArray[0]){ flipArray.shift(); document.getElementById("card7").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElSeven) && numElSeven === flipArray[1]){ flipArray.pop();  document.getElementById("card7").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElSeven)){flipArray.push(numElSeven); card7.src = cardSelect[numElSeven - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealEight(){
    if(tableArray.length > 51){ 
let numElEight = tableArrayIndex[7]

if(flipArray.includes(numElEight) && numElEight === flipArray[0]){ flipArray.shift(); document.getElementById("card8").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElEight) && numElEight === flipArray[1]){ flipArray.pop();  document.getElementById("card8").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElEight)){flipArray.push(numElEight); card8.src = cardSelect[numElEight - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}


 function revealNine(){
    if(tableArray.length > 51){ 
let numElNine = tableArrayIndex[8]

if(flipArray.includes(numElNine) && numElNine === flipArray[0]){ flipArray.shift(); document.getElementById("card9").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElNine) && numElNine === flipArray[1]){ flipArray.pop();  document.getElementById("card9").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElNine)){flipArray.push(numElNine); card9.src = cardSelect[numElNine - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealTen(){
    if(tableArray.length > 51){ 
let numElTen = tableArrayIndex[9]

if(flipArray.includes(numElTen) && numElTen === flipArray[0]){ flipArray.shift(); document.getElementById("card10").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTen) && numElTen === flipArray[1]){ flipArray.pop();  document.getElementById("card10").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTen)){flipArray.push(numElTen); card10.src = cardSelect[numElTen - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealEleven(){
    if(tableArray.length > 51){ 
let numElEleven = tableArrayIndex[10]

if(flipArray.includes(numElEleven) && numElEleven === flipArray[0]){ flipArray.shift(); document.getElementById("card11").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElEleven) && numElEleven === flipArray[1]){ flipArray.pop();  document.getElementById("card11").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElEleven)){flipArray.push(numElEleven); card11.src = cardSelect[numElEleven - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealTwelve(){
    if(tableArray.length > 51){
let numElTwelve = tableArrayIndex[11]

if(flipArray.includes(numElTwelve) && numElTwelve === flipArray[0]){ flipArray.shift(); document.getElementById("card12").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTwelve) && numElTwelve === flipArray[1]){ flipArray.pop();  document.getElementById("card12").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTwelve)){flipArray.push(numElTwelve); card12.src = cardSelect[numElTwelve - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealThirteen(){
    if(tableArray.length > 51){ 
let numElThirteen = tableArrayIndex[12]

if(flipArray.includes(numElThirteen) && numElThirteen === flipArray[0]){ flipArray.shift(); document.getElementById("card13").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirteen) && numElThirteen === flipArray[1]){ flipArray.pop();  document.getElementById("card13").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirteen)){flipArray.push(numElThirteen); card13.src = cardSelect[numElThirteen - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}


// next row of cards - row 2

function revealFourteen(){
    if(tableArray.length > 51){ 
let numElFourteen = tableArrayIndex[13];

if(flipArray.includes(numElFourteen) && numElFourteen === flipArray[0]){ flipArray.shift(); document.getElementById("card14").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFourteen) && numElFourteen === flipArray[1]){ flipArray.pop();  document.getElementById("card14").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFourteen)){flipArray.push(numElFourteen); card14.src = cardSelect[numElFourteen - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}

   



function revealFifteen(){
    if(tableArray.length > 51){ 
let numElFifteen = tableArrayIndex[14]

if(flipArray.includes(numElFifteen) && numElFifteen === flipArray[0]){ flipArray.shift(); document.getElementById("card15").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFifteen) && numElFifteen === flipArray[1]){ flipArray.pop();  document.getElementById("card15").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFifteen)){flipArray.push(numElFifteen); card15.src = cardSelect[numElFifteen - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}





function revealSixteen(){
    if(tableArray.length > 51){ 
    let numElSixteen = tableArrayIndex[15]
    
    if(flipArray.includes(numElSixteen) && numElSixteen === flipArray[0]){ flipArray.shift(); document.getElementById("card16").src="card back red.jpg"; playSound();} 
    else if(flipArray.includes(numElSixteen) && numElSixteen === flipArray[1]){ flipArray.pop();  document.getElementById("card16").src="card back red.jpg"; playSound();}
    else{revealCard()}
    
    function revealCard(){
    if (flipArray.length < 2 && !pairsArray.includes(numElSixteen)){flipArray.push(numElSixteen); card16.src = cardSelect[numElSixteen - 1]; playSound();}
    //console.log(flipArray)
    pairFound()
    }}}
    




function revealSevenTeen(){
    if(tableArray.length > 51){ 
let numElSeventeen = tableArrayIndex[16]

if(flipArray.includes(numElSeventeen) && numElSeventeen === flipArray[0]){ flipArray.shift(); document.getElementById("card17").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElSeventeen) && numElSeventeen === flipArray[1]){ flipArray.pop();  document.getElementById("card17").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElSeventeen)){flipArray.push(numElSeventeen); card17.src = cardSelect[numElSeventeen - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}





 function revealEighteen(){
    if(tableArray.length > 51){ 
let numElEighteen = tableArrayIndex[17]

if(flipArray.includes(numElEighteen) && numElEighteen === flipArray[0]){ flipArray.shift(); document.getElementById("card18").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElEighteen) && numElEighteen === flipArray[1]){ flipArray.pop();  document.getElementById("card18").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElEighteen)){flipArray.push(numElEighteen); card18.src = cardSelect[numElEighteen - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}





 function revealNineteen(){
    if(tableArray.length > 51){
let numElNineteen = tableArrayIndex[18]

if(flipArray.includes(numElNineteen) && numElNineteen === flipArray[0]){ flipArray.shift(); document.getElementById("card19").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElNineteen) && numElNineteen === flipArray[1]){ flipArray.pop();  document.getElementById("card19").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElNineteen)){flipArray.push(numElNineteen); card19.src = cardSelect[numElNineteen - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealTwenty(){
    if(tableArray.length > 51){
let numElTwenty = tableArrayIndex[19]

if(flipArray.includes(numElTwenty) && numElTwenty === flipArray[0]){ flipArray.shift(); document.getElementById("card20").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTwenty) && numElTwenty === flipArray[1]){ flipArray.pop();  document.getElementById("card20").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTwenty)){flipArray.push(numElTwenty); card20.src = cardSelect[numElTwenty - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealTwentyOne(){
    if(tableArray.length > 51){ 
let numElTwentyOne = tableArrayIndex[20]

if(flipArray.includes(numElTwentyOne) && numElTwentyOne === flipArray[0]){ flipArray.shift(); document.getElementById("card21").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTwentyOne) && numElTwentyOne === flipArray[1]){ flipArray.pop();  document.getElementById("card21").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTwentyOne)){flipArray.push(numElTwentyOne); card21.src = cardSelect[numElTwentyOne - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealTwentyTwo(){
    if(tableArray.length > 51){ 
let numElTwentyTwo = tableArrayIndex[21]

if(flipArray.includes(numElTwentyTwo) && numElTwentyTwo === flipArray[0]){ flipArray.shift(); document.getElementById("card22").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTwentyTwo) && numElTwentyTwo === flipArray[1]){ flipArray.pop();  document.getElementById("card22").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTwentyTwo)){flipArray.push(numElTwentyTwo); card22.src = cardSelect[numElTwentyTwo - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealTwentyThree(){
    if(tableArray.length > 51){ 
let numElTwentyThree = tableArrayIndex[22]

if(flipArray.includes(numElTwentyThree) && numElTwentyThree === flipArray[0]){ flipArray.shift(); document.getElementById("card23").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTwentyThree) && numElTwentyThree === flipArray[1]){ flipArray.pop();  document.getElementById("card23").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTwentyThree)){flipArray.push(numElTwentyThree); card23.src = cardSelect[numElTwentyThree - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealTwentyFour(){
    if(tableArray.length > 51){ 
let numElTwentyFour = tableArrayIndex[23]

if(flipArray.includes(numElTwentyFour) && numElTwentyFour === flipArray[0]){ flipArray.shift(); document.getElementById("card24").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTwentyFour) && numElTwentyFour === flipArray[1]){ flipArray.pop();  document.getElementById("card24").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTwentyFour)){flipArray.push(numElTwentyFour); card24.src = cardSelect[numElTwentyFour - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealTwentyFive(){
    if(tableArray.length > 51){ 
let numElTTwentyFive = tableArrayIndex[24]

if(flipArray.includes(numElTTwentyFive) && numElTTwentyFive === flipArray[0]){ flipArray.shift(); document.getElementById("card25").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTTwentyFive) && numElTTwentyFive === flipArray[1]){ flipArray.pop();  document.getElementById("card25").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTTwentyFive)){flipArray.push(numElTTwentyFive); card25.src = cardSelect[numElTTwentyFive - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealTwentySix(){
    if(tableArray.length > 51){ 
let numElTwentySix = tableArrayIndex[25]

if(flipArray.includes(numElTwentySix) && numElTwentySix === flipArray[0]){ flipArray.shift(); document.getElementById("card26").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTwentySix) && numElTwentySix === flipArray[1]){ flipArray.pop();  document.getElementById("card26").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTwentySix)){flipArray.push(numElTwentySix); card26.src = cardSelect[numElTwentySix - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}


// next row of cards - row 3



function revealTwentySeven(){
    if(tableArray.length > 51){ 
let numElTwentySeven = tableArrayIndex[26];

if(flipArray.includes(numElTwentySeven) && numElTwentySeven === flipArray[0]){ flipArray.shift(); document.getElementById("card27").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTwentySeven) && numElTwentySeven === flipArray[1]){ flipArray.pop();  document.getElementById("card27").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTwentySeven)){flipArray.push(numElTwentySeven); card27.src = cardSelect[numElTwentySeven - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}
   



function revealTwentyEight(){
    if(tableArray.length > 51){ 
let numElTwentyEight = tableArrayIndex[27]

if(flipArray.includes(numElTwentyEight) && numElTwentyEight === flipArray[0]){ flipArray.shift(); document.getElementById("card28").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElTwentyEight) && numElTwentyEight === flipArray[1]){ flipArray.pop();  document.getElementById("card28").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElTwentyEight)){flipArray.push(numElTwentyEight); card28.src = cardSelect[numElTwentyEight - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




function revealTwentyNine(){
    if(tableArray.length > 51){ 
    let numElTwentyNine = tableArrayIndex[28]
    
    if(flipArray.includes(numElTwentyNine) && numElTwentyNine === flipArray[0]){ flipArray.shift(); document.getElementById("card29").src="card back red.jpg"; playSound();} 
    else if(flipArray.includes(numElTwentyNine) && numElTwentyNine === flipArray[1]){ flipArray.pop();  document.getElementById("card29").src="card back red.jpg"; playSound();}
    else{revealCard()}
    
    function revealCard(){
    if (flipArray.length < 2 && !pairsArray.includes(numElTwentyNine)){flipArray.push(numElTwentyNine); card29.src = cardSelect[numElTwentyNine - 1]; playSound();}
    //console.log(flipArray)
    pairFound()
    }}}




function revealThirty(){
    if(tableArray.length > 51){ 
let numElThirty = tableArrayIndex[29]

if(flipArray.includes(numElThirty) && numElThirty === flipArray[0]){ flipArray.shift(); document.getElementById("card30").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirty) && numElThirty === flipArray[1]){ flipArray.pop();  document.getElementById("card30").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirty)){flipArray.push(numElThirty); card30.src = cardSelect[numElThirty - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealThirtyOne(){
    if(tableArray.length > 51){ 
let numElThirtyOne = tableArrayIndex[30]

if(flipArray.includes(numElThirtyOne) && numElThirtyOne === flipArray[0]){ flipArray.shift(); document.getElementById("card31").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirtyOne) && numElThirtyOne === flipArray[1]){ flipArray.pop();  document.getElementById("card31").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirtyOne)){flipArray.push(numElThirtyOne); card31.src = cardSelect[numElThirtyOne - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}





 function revealThirtyTwo(){
    if(tableArray.length > 51){ 
let numElThirtyTwo = tableArrayIndex[31]

if(flipArray.includes(numElThirtyTwo) && numElThirtyTwo === flipArray[0]){ flipArray.shift(); document.getElementById("card32").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirtyTwo) && numElThirtyTwo === flipArray[1]){ flipArray.pop();  document.getElementById("card32").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirtyTwo)){flipArray.push(numElThirtyTwo); card32.src = cardSelect[numElThirtyTwo - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealThirtyThree(){
    if(tableArray.length > 51){ 
let numElThirtyThree = tableArrayIndex[32]

if(flipArray.includes(numElThirtyThree) && numElThirtyThree === flipArray[0]){ flipArray.shift(); document.getElementById("card33").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirtyThree) && numElThirtyThree === flipArray[1]){ flipArray.pop();  document.getElementById("card33").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirtyThree)){flipArray.push(numElThirtyThree); card33.src = cardSelect[numElThirtyThree - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealThirtyFour(){
    if(tableArray.length > 51){ 
let numElThirtyFour = tableArrayIndex[33]

if(flipArray.includes(numElThirtyFour) && numElThirtyFour === flipArray[0]){ flipArray.shift(); document.getElementById("card34").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirtyFour) && numElThirtyFour === flipArray[1]){ flipArray.pop();  document.getElementById("card34").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirtyFour)){flipArray.push(numElThirtyFour); card34.src = cardSelect[numElThirtyFour - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealThirtyFive(){
    if(tableArray.length > 51){ 
let numElThirtyFive = tableArrayIndex[34]

if(flipArray.includes(numElThirtyFive) && numElThirtyFive === flipArray[0]){ flipArray.shift(); document.getElementById("card35").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirtyFive) && numElThirtyFive === flipArray[1]){ flipArray.pop();  document.getElementById("card35").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirtyFive)){flipArray.push(numElThirtyFive); card35.src = cardSelect[numElThirtyFive - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealThirtySix(){
    if(tableArray.length > 51){ 
let numElThirtySix = tableArrayIndex[35]

if(flipArray.includes(numElThirtySix) && numElThirtySix === flipArray[0]){ flipArray.shift(); document.getElementById("card36").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirtySix) && numElThirtySix === flipArray[1]){ flipArray.pop();  document.getElementById("card36").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirtySix)){flipArray.push(numElThirtySix); card36.src = cardSelect[numElThirtySix - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealThirtySeven(){
    if(tableArray.length > 51){ 
let numElThirtySeven = tableArrayIndex[36]

if(flipArray.includes(numElThirtySeven) && numElThirtySeven === flipArray[0]){ flipArray.shift(); document.getElementById("card37").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirtySeven) && numElThirtySeven === flipArray[1]){ flipArray.pop();  document.getElementById("card37").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirtySeven)){flipArray.push(numElThirtySeven); card37.src = cardSelect[numElThirtySeven - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealThirtyEight(){
    if(tableArray.length > 51){ 
let numElThirtyEight = tableArrayIndex[37]

if(flipArray.includes(numElThirtyEight) && numElThirtyEight === flipArray[0]){ flipArray.shift(); document.getElementById("card38").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirtyEight) && numElThirtyEight === flipArray[1]){ flipArray.pop();  document.getElementById("card38").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirtyEight)){flipArray.push(numElThirtyEight); card38.src = cardSelect[numElThirtyEight - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealThirtyNine(){
    if(tableArray.length > 51){ 
let numElThirtyNine = tableArrayIndex[38]

if(flipArray.includes(numElThirtyNine) && numElThirtyNine === flipArray[0]){ flipArray.shift(); document.getElementById("card39").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElThirtyNine) && numElThirtyNine === flipArray[1]){ flipArray.pop();  document.getElementById("card39").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElThirtyNine)){flipArray.push(numElThirtyNine); card39.src = cardSelect[numElThirtyNine - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}


// next row of cards - row 4




function revealForty(){
    if(tableArray.length > 51){ 
let numElForty = tableArrayIndex[39];

if(flipArray.includes(numElForty) && numElForty === flipArray[0]){ flipArray.shift(); document.getElementById("card40").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElForty) && numElForty === flipArray[1]){ flipArray.pop();  document.getElementById("card40").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElForty)){flipArray.push(numElForty); card40.src = cardSelect[numElForty - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}

   



function revealFortyOne(){
    if(tableArray.length > 51){ 
let numElFortyOne = tableArrayIndex[40]

if(flipArray.includes(numElFortyOne) && numElFortyOne === flipArray[0]){ flipArray.shift(); document.getElementById("card41").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFortyOne) && numElFortyOne === flipArray[1]){ flipArray.pop();  document.getElementById("card41").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFortyOne)){flipArray.push(numElFortyOne); card41.src = cardSelect[numElFortyOne - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




function revealFortyTwo(){
    if(tableArray.length > 51){ 
    let numElFortyTwo = tableArrayIndex[41]
    
    if(flipArray.includes(numElFortyTwo) && numElFortyTwo === flipArray[0]){ flipArray.shift(); document.getElementById("card42").src="card back red.jpg"; playSound();} 
    else if(flipArray.includes(numElFortyTwo) && numElFortyTwo === flipArray[1]){ flipArray.pop();  document.getElementById("card42").src="card back red.jpg"; playSound();}
    else{revealCard()}
    
    function revealCard(){
    if (flipArray.length < 2 && !pairsArray.includes(numElFortyTwo)){flipArray.push(numElFortyTwo); card42.src = cardSelect[numElFortyTwo - 1]; playSound();}
    //console.log(flipArray)
    pairFound()
    }}}




function revealFortyThree(){
    if(tableArray.length > 51){ 
let numElFortyThree = tableArrayIndex[42]

if(flipArray.includes(numElFortyThree) && numElFortyThree === flipArray[0]){ flipArray.shift(); document.getElementById("card43").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFortyThree) && numElFortyThree === flipArray[1]){ flipArray.pop();  document.getElementById("card43").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFortyThree)){flipArray.push(numElFortyThree); card43.src = cardSelect[numElFortyThree - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealFortyFour(){
    if(tableArray.length > 51){ 
let numElFortyFour = tableArrayIndex[43]

if(flipArray.includes(numElFortyFour) && numElFortyFour === flipArray[0]){ flipArray.shift(); document.getElementById("card44").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFortyFour) && numElFortyFour === flipArray[1]){ flipArray.pop();  document.getElementById("card44").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFortyFour)){flipArray.push(numElFortyFour); card44.src = cardSelect[numElFortyFour - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}




 function revealFortyFive(){
    if(tableArray.length > 51){ 
let numElFortyFive = tableArrayIndex[44]

if(flipArray.includes(numElFortyFive) && numElFortyFive === flipArray[0]){ flipArray.shift(); document.getElementById("card45").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFortyFive) && numElFortyFive === flipArray[1]){ flipArray.pop();  document.getElementById("card45").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFortyFive)){flipArray.push(numElFortyFive); card45.src = cardSelect[numElFortyFive - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealFortySix(){
    if(tableArray.length > 51){ 
let numElFortySix = tableArrayIndex[45]

if(flipArray.includes(numElFortySix) && numElFortySix === flipArray[0]){ flipArray.shift(); document.getElementById("card46").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFortySix) && numElFortySix === flipArray[1]){ flipArray.pop();  document.getElementById("card46").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFortySix)){flipArray.push(numElFortySix); card46.src = cardSelect[numElFortySix - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealFortySeven(){
    if(tableArray.length > 51){
let numElFortySeven = tableArrayIndex[46]

if(flipArray.includes(numElFortySeven) && numElFortySeven === flipArray[0]){ flipArray.shift(); document.getElementById("card47").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFortySeven) && numElFortySeven === flipArray[1]){ flipArray.pop();  document.getElementById("card47").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFortySeven)){flipArray.push(numElFortySeven); card47.src = cardSelect[numElFortySeven - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealFortyEight(){
    if(tableArray.length > 51){ 
let numElFortyEight = tableArrayIndex[47]

if(flipArray.includes(numElFortyEight) && numElFortyEight === flipArray[0]){ flipArray.shift(); document.getElementById("card48").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFortyEight) && numElFortyEight === flipArray[1]){ flipArray.pop();  document.getElementById("card48").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFortyEight)){flipArray.push(numElFortyEight); card48.src = cardSelect[numElFortyEight - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealFortyNine(){
    if(tableArray.length > 51){ 
let numElFortyNine = tableArrayIndex[48]

if(flipArray.includes(numElFortyNine) && numElFortyNine === flipArray[0]){ flipArray.shift(); document.getElementById("card49").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFortyNine) && numElFortyNine === flipArray[1]){ flipArray.pop();  document.getElementById("card49").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFortyNine)){flipArray.push(numElFortyNine); card49.src = cardSelect[numElFortyNine - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealFifty(){
    if(tableArray.length > 51){ 
let numElFifty = tableArrayIndex[49]

if(flipArray.includes(numElFifty) && numElFifty === flipArray[0]){ flipArray.shift(); document.getElementById("card50").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFifty) && numElFifty === flipArray[1]){ flipArray.pop();  document.getElementById("card50").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFifty)){flipArray.push(numElFifty); card50.src = cardSelect[numElFifty - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealFiftyOne(){
    if(tableArray.length > 51){ 
let numElFiftyOne = tableArrayIndex[50]

if(flipArray.includes(numElFiftyOne) && numElFiftyOne === flipArray[0]){ flipArray.shift(); document.getElementById("card51").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFiftyOne) && numElFiftyOne === flipArray[1]){ flipArray.pop();  document.getElementById("card51").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFiftyOne)){flipArray.push(numElFiftyOne); card51.src = cardSelect[numElFiftyOne - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}



 function revealFiftyTwo(){
    if(tableArray.length > 51){ 
let numElFiftyTwo = tableArrayIndex[51]

if(flipArray.includes(numElFiftyTwo) && numElFiftyTwo === flipArray[0]){ flipArray.shift(); document.getElementById("card52").src="card back red.jpg"; playSound();} 
else if(flipArray.includes(numElFiftyTwo) && numElFiftyTwo === flipArray[1]){ flipArray.pop();  document.getElementById("card52").src="card back red.jpg"; playSound();}
else{revealCard()}

function revealCard(){
if (flipArray.length < 2 && !pairsArray.includes(numElFiftyTwo)){flipArray.push(numElFiftyTwo); card52.src = cardSelect[numElFiftyTwo - 1]; playSound();}
//console.log(flipArray)
pairFound()
}}}