let cardSelect = [ 
"1.png","2.png","3.png","4.png",
"4.png","6.png","7.png","8.png",
"9.png","10.png","11.png","12.png",
"13.png","14.png","15.png","16.png",
"17.png","18.png","19.png","20.png",
"21.png","22.png","23.png","24.png",
"25.png","26.png","27.png","28.png",
"29.png","30.png","31.png","32.png",
"33.png","34.png","35.png","36.png",
"37.png","38.png","39.png","40.png",
"41.png","42.png","43.png","44.png",
"45.png","46.png","47.png","48.png",
"49.png","50.png","51.png","52.png",]



let flipArray = [] // will enter pairs of cards here and compare
var pair1; 
var pair2; 
let tableArrayIndex = []// using this to turn the picked cards back to integer numbers
let cardSuitsArray = []; // for available suits
let cardNumbersArray = []; // for available card values
let randomSuitNum = "";// variable for generated suit index
let randomSuit = "";// variable for suit name
let randomCardNum = "";// variable for generated number
let chosenCard = "" // variable for generated number and suit combined - picked card
let tableArray = []; // cards dealt to table
let displayEl = document.getElementById('display');// picked card display

// function for card generation
function pickCard(){
if(tableArray.length < 52){
cardSuitsArray = ["clubs","diamonds","hearts","spades"] // all suits 
cardNumbersArray = [1,2,3,4,5,6,7,8,9,10,11,12,13] // all card values
randomSuitNum = Math.floor(Math.random()*cardSuitsArray.length)//suit generated by index
randomCardNum = Math.ceil(Math.random()*cardNumbersArray.length) // card value generated
randomSuit = cardSuitsArray[randomSuitNum]// suit name picked from generated index
chosenCard = randomCardNum + randomSuit // variable for value and suit of card
let  actualCard = randomSuitNum + 1 + (4*(randomCardNum - 1)) //this turns the named cards into numbers from 1-52

// condition to prevent duplicate card generation; if duplicate generated, re-run pickCard()
if(tableArray.includes(chosenCard)){pickCard();} 
else{
tableArrayIndex.push(actualCard)
tableArray.push(chosenCard) // card pushed to table
displayEl.textContent =  chosenCard +   ","; // card displayed

}
}

logArray()
shuffleCards()

}


function logArray(){
if (tableArrayIndex.length > 51){console.log(tableArrayIndex)}
 if (tableArray.length > 51){console.log(tableArray)}// this logs each named card in the tableArray (after it is relabeled as an integer value) as an indexed number which can be used to pull the card images, which themselves are labeled as integers. 

}


function shuffleCards(){
if (tableArray.length < 52){ pickCard()} //picks and pushes next card to array until 52 cards are picked

}

/*

var numEl;
if (numEl = tableArrayIndex[0]){tableArrayIndex.pop(numEl); card#.src = card back red.jpg)} else{
 numEl = tableArrayIndex[0]
card1.src = cardSelect[numEl - 1] }
if ( flipArray.length < 3 ){flipArray.push(numEl)}
*/

// firstt row of cards - row 1

function revealOne(){
    if(tableArray.length > 51){
let numElOne = tableArrayIndex[0];
if ( flipArray.includes(numElOne)){ flipArray.pop(numElOne); document.getElementById("card1").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElOne); card1.src = cardSelect[numElOne - 1]}
console.log(flipArray);
pair1 = Math.ceil(flipArray[0]/4)
pair2 = Math.ceil(flipArray[1]/4)
if (pair1 = pair2){console.log("pair found")}
 }}}
   



function revealTwo(){
    if(tableArray.length > 51){
let numElTwo = tableArrayIndex[1]

if ( flipArray.includes(numElTwo)){ flipArray.pop(numElTwo); document.getElementById("card2").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwo); card2.src = cardSelect[numElTwo - 1]}
console.log(flipArray)
pair1 = Math.ceil(flipArray[0]/4)
pair2 = Math.ceil(flipArray[1]/4)
if (pair1 = pair2){console.log("pair found")}
 }}}




function revealThree(){
    if(tableArray.length > 51){
    let numElThree = tableArrayIndex[2]
    
    if ( flipArray.includes(numElThree)){ flipArray.pop(numElThree); document.getElementById("card3").src="card back red.jpg";} 
    else{revealCard()}
   
   function revealCard(){
   if (flipArray.length < 2){flipArray.push(numElThree); card3.src = cardSelect[numElThree - 1]}
   console.log(flipArray)
   pair1 = Math.ceil(flipArray[0]/4)
pair2 = Math.ceil(flipArray[1]/4)
if (pair1 = pair2){console.log("pair found")}
    }}}




function revealFour(){
    if(tableArray.length > 51){
let numElFour = tableArrayIndex[3]

if ( flipArray.includes(numElFour)){ flipArray.pop(numElFour); document.getElementById("card4").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFour); card4.src = cardSelect[numElFour - 1]}
console.log(flipArray)
 }}}




 function revealFive(){
    if(tableArray.length > 51){
let numElFive = tableArrayIndex[4]

if ( flipArray.includes(numElFive)){ flipArray.pop(numElFive); document.getElementById("card5").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFive); card5.src = cardSelect[numElFive - 1]}
console.log(flipArray)
 }}}




 function revealSix(){
    if(tableArray.length > 51){
let numElSix = tableArrayIndex[5]

if ( flipArray.includes(numElSix)){ flipArray.pop(numElSix); document.getElementById("card6").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElSix); card6.src = cardSelect[numElSix - 1]}
console.log(flipArray)
 }}}



 function revealSeven(){
    if(tableArray.length > 51){
let numElSeven = tableArrayIndex[6]

if ( flipArray.includes(numElSeven)){ flipArray.pop(numElSeven); document.getElementById("card7").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElSeven); card7.src = cardSelect[numElSeven - 1]}
console.log(flipArray)
 }}}



 function revealEight(){
    if(tableArray.length > 51){
let numElEight = tableArrayIndex[7]

if ( flipArray.includes(numElEight)){ flipArray.pop(numElEight); document.getElementById("card8").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElEight); card8.src = cardSelect[numElEight - 1]}
console.log(flipArray)
 }}}



 function revealNine(){
    if(tableArray.length > 51){
let numElNine = tableArrayIndex[8]

if ( flipArray.includes(numElNine)){ flipArray.pop(numElNine); document.getElementById("card9").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElNine); card9.src = cardSelect[numElNine - 1]}
console.log(flipArray)
 }}}



 function revealTen(){
    if(tableArray.length > 51){
let numElTen = tableArrayIndex[9]

if ( flipArray.includes(numElTen)){ flipArray.pop(numElTen); document.getElementById("card10").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTen); card10.src = cardSelect[numElTen - 1]}
console.log(flipArray)
 }}}



 function revealEleven(){
    if(tableArray.length > 51){
let numElEleven = tableArrayIndex[10]

if ( flipArray.includes(numElEleven)){ flipArray.pop(numElEleven); document.getElementById("card11").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElEleven); card11.src = cardSelect[numElEleven - 1]}
console.log(flipArray)
 }}}



 function revealTwelve(){
    if(tableArray.length > 51){
let numElTwelve = tableArrayIndex[11]

if ( flipArray.includes(numElTwelve)){ flipArray.pop(numElTwelve); document.getElementById("card12").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwelve); card12.src = cardSelect[numElTwelve - 1]}
console.log(flipArray)
 }}}



 function revealThirteen(){
    if(tableArray.length > 51){
let numElThirteen = tableArrayIndex[12]

if ( flipArray.includes(numElThirteen)){ flipArray.pop(numElThirteen); document.getElementById("card13").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirteen); card13.src = cardSelect[numElThirteen - 1]}
console.log(flipArray)
 }}}


// next row of cards - row 2

function revealFourteen(){
    if(tableArray.length > 51){
let numElFourteen = tableArrayIndex[13];
if ( flipArray.includes(numElFourteen)){ flipArray.pop(numElFourteen); document.getElementById("card14").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFourteen); card14.src = cardSelect[numElFourteen - 1]}
console.log(flipArray)
 }}}
   



function revealFifteen(){
    if(tableArray.length > 51){
let numElFifteen = tableArrayIndex[14]

if ( flipArray.includes(numElFifteen)){ flipArray.pop(numElFifteen); document.getElementById("card15").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFifteen); card15.src = cardSelect[numElFifteen - 1]}
console.log(flipArray)
 }}}




function revealSixteen(){
    if(tableArray.length > 51){
    let numElSixteen = tableArrayIndex[15]
    
    if ( flipArray.includes(numElSixteen)){ flipArray.pop(numElSixteen); document.getElementById("card16").src="card back red.jpg";} 
    else{revealCard()}
   
   function revealCard(){
   if (flipArray.length < 2){flipArray.push(numElSixteen); card16.src = cardSelect[numElSixteen - 1]}
   console.log(flipArray)
    }}}




function revealSevenTeen(){
    if(tableArray.length > 51){
let numElSeventeen = tableArrayIndex[16]

if ( flipArray.includes(numElSeventeen)){ flipArray.pop(numElSeventeen); document.getElementById("card17").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElSeventeen); card17.src = cardSelect[numElSeventeen - 1]}
console.log(flipArray)
 }}}




 function revealEighteen(){
    if(tableArray.length > 51){
let numElEighteen = tableArrayIndex[17]

if ( flipArray.includes(numElEighteen)){ flipArray.pop(numElEighteen); document.getElementById("card18").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElEighteen); card18.src = cardSelect[numElEighteen - 1]}
console.log(flipArray)
 }}}




 function revealNineteen(){
    if(tableArray.length > 51){
let numElNineteen = tableArrayIndex[18]

if ( flipArray.includes(numElNineteen)){ flipArray.pop(numElNineteen); document.getElementById("card19").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElNineteen); card19.src = cardSelect[numElNineteen - 1]}
console.log(flipArray)
 }}}



 function revealTwenty(){
    if(tableArray.length > 51){
let numElTwenty = tableArrayIndex[19]

if ( flipArray.includes(numElTwenty)){ flipArray.pop(numElTwenty); document.getElementById("card20").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwenty); card20.src = cardSelect[numElTwenty - 1]}
console.log(flipArray)
 }}}



 function revealTwentyOne(){
    if(tableArray.length > 51){
let numElTwentyOne = tableArrayIndex[20]

if ( flipArray.includes(numElTwentyOne)){ flipArray.pop(numElTwentyOne); document.getElementById("card21").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwentyOne); card21.src = cardSelect[numElTwentyOne - 1]}
console.log(flipArray)
 }}}



 function revealTwentyTwo(){
    if(tableArray.length > 51){
let numElTwentyTwo = tableArrayIndex[21]

if ( flipArray.includes(numElTwentyTwo)){ flipArray.pop(numElTwentyTwo); document.getElementById("card22").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwentyTwo); card22.src = cardSelect[numElTwentyTwo - 1]}
console.log(flipArray)
 }}}



 function revealTwentyThree(){
    if(tableArray.length > 51){
let numElTwentyThree = tableArrayIndex[22]

if ( flipArray.includes(numElTwentyThree)){ flipArray.pop(numElTwentyThree); document.getElementById("card23").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwentyThree); card23.src = cardSelect[numElTwentyThree - 1]}
console.log(flipArray)
 }}}



 function revealTwentyFour(){
    if(tableArray.length > 51){
let numElTwentyFour = tableArrayIndex[23]

if ( flipArray.includes(numElTwentyFour)){ flipArray.pop(numElTwentyFour); document.getElementById("card24").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwentyFour); card24.src = cardSelect[numElTwentyFour - 1]}
console.log(flipArray)
 }}}



 function revealTwentyFive(){
    if(tableArray.length > 51){
let numElTTwentyFive = tableArrayIndex[24]

if ( flipArray.includes(numElTTwentyFive)){ flipArray.pop(numElTTwentyFive); document.getElementById("card25").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTTwentyFive); card25.src = cardSelect[numElTTwentyFive - 1]}
console.log(flipArray)
 }}}



 function revealTwentySix(){
    if(tableArray.length > 51){
let numElTwentySix = tableArrayIndex[25]

if ( flipArray.includes(numElTwentySix)){ flipArray.pop(numElTwentySix); document.getElementById("card26").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwentySix); card26.src = cardSelect[numElTwentySix - 1]}
console.log(flipArray)
 }}}


// next row of cards - row 3



function revealTwentySeven(){
    if(tableArray.length > 51){
let numElTwentySeven = tableArrayIndex[26];

if ( flipArray.includes(numElTwentySeven)){ flipArray.pop(numElTwentySeven); document.getElementById("card27").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwentySeven); card27.src = cardSelect[numElTwentySeven - 1]}
console.log(flipArray)
 }}}
   



function revealTwentyEight(){
    if(tableArray.length > 51){
let numElTwentyEight = tableArrayIndex[27]

if ( flipArray.includes(numElTwentyEight)){ flipArray.pop(numElTwentyEight); document.getElementById("card28").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElTwentyEight); card28.src = cardSelect[numElTwentyEight - 1]}
console.log(flipArray)
 }}}




function revealTwentyNine(){
    if(tableArray.length > 51){
    let numElTwentyNine = tableArrayIndex[28]
    
    if ( flipArray.includes(numElTwentyNine)){ flipArray.pop(numElTwentyNine); document.getElementById("card29").src="card back red.jpg";} 
    else{revealCard()}
   
   function revealCard(){
   if (flipArray.length < 2){flipArray.push(numElTwentyNine); card29.src = cardSelect[numElTwentyNine - 1]}
   console.log(flipArray)
    }}}




function revealThirty(){
    if(tableArray.length > 51){
let numElThirty = tableArrayIndex[29]

if ( flipArray.includes(numElThirty)){ flipArray.pop(numElThirty); document.getElementById("card30").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirty); card30.src = cardSelect[numElThirty - 1]}
console.log(flipArray)
 }}}




 function revealThirtyOne(){
    if(tableArray.length > 51){
let numElThirtyOne = tableArrayIndex[30]

if ( flipArray.includes(numElThirtyOne)){ flipArray.pop(numElThirtyOne); document.getElementById("card31").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirtyOne); card31.src = cardSelect[numElThirtyOne - 1]}
console.log(flipArray)
 }}}




 function revealThirtyTwo(){
    if(tableArray.length > 51){
let numElThirtyTwo = tableArrayIndex[31]

if ( flipArray.includes(numElThirtyTwo)){ flipArray.pop(numElThirtyTwo); document.getElementById("card32").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirtyTwo); card32.src = cardSelect[numElThirtyTwo - 1]}
console.log(flipArray)
 }}}



 function revealThirtyThree(){
    if(tableArray.length > 51){
let numElThirtyThree = tableArrayIndex[32]

if ( flipArray.includes(numElThirtyThree)){ flipArray.pop(numElThirtyThree); document.getElementById("card33").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirtyThree); card33.src = cardSelect[numElThirtyThree - 1]}
console.log(flipArray)
 }}}



 function revealThirtyFour(){
    if(tableArray.length > 51){
let numElThirtyFour = tableArrayIndex[33]

if ( flipArray.includes(numElThirtyFour)){ flipArray.pop(numElThirtyFour); document.getElementById("card34").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirtyFour); card34.src = cardSelect[numElThirtyFour - 1]}
console.log(flipArray)
 }}}



 function revealThirtyFive(){
    if(tableArray.length > 51){
let numElThirtyFive = tableArrayIndex[34]

if ( flipArray.includes(numElThirtyFive)){ flipArray.pop(numElThirtyFive); document.getElementById("card35").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirtyFive); card35.src = cardSelect[numElThirtyFive - 1]}
console.log(flipArray)
 }}}



 function revealThirtySix(){
    if(tableArray.length > 51){
let numElThirtySix = tableArrayIndex[35]

if ( flipArray.includes(numElThirtySix)){ flipArray.pop(numElThirtySix); document.getElementById("card36").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirtySix); card36.src = cardSelect[numElThirtySix- 1]}
console.log(flipArray)
 }}}



 function revealThirtySeven(){
    if(tableArray.length > 51){
let numElThirtySeven = tableArrayIndex[36]

if ( flipArray.includes(numElThirtySeven)){ flipArray.pop(numElThirtySeven); document.getElementById("card37").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirtySeven); card37.src = cardSelect[numElThirtySeven - 1]}
console.log(flipArray)
 }}}



 function revealThirtyEight(){
    if(tableArray.length > 51){
let numElThirtyEight = tableArrayIndex[37]

if ( flipArray.includes(numElThirtyEight)){ flipArray.pop(numElThirtyEight); document.getElementById("card38").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirtyEight); card38.src = cardSelect[numElThirtyEight - 1]}
console.log(flipArray)
 }}}



 function revealThirtyNine(){
    if(tableArray.length > 51){
let numElThirtyNine = tableArrayIndex[38]

if ( flipArray.includes(numElThirtyNine)){ flipArray.pop(numElThirtyNine); document.getElementById("card39").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElThirtyNine); card39.src = cardSelect[numElThirtyNine - 1]}
console.log(flipArray)
 }}}

// next row of cards - row 4




function revealForty(){
    if(tableArray.length > 51){
let numElForty = tableArrayIndex[39];

if ( flipArray.includes(numElForty)){ flipArray.pop(numElForty); document.getElementById("card40").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElForty); card40.src = cardSelect[numElForty - 1]}
console.log(flipArray)
 }}}
   



function revealFortyOne(){
    if(tableArray.length > 51){
let numElFortyOne = tableArrayIndex[40]

if ( flipArray.includes(numElFortyOne)){ flipArray.pop(numElFortyOne); document.getElementById("card41").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFortyOne); card41.src = cardSelect[numElFortyOne - 1]}
console.log(flipArray)
 }}}




function revealFortyTwo(){
    if(tableArray.length > 51){
    let numElFortyTwo = tableArrayIndex[41]
    
    if ( flipArray.includes(numElFortyTwo)){ flipArray.pop(numElFortyTwo); document.getElementById("card42").src="card back red.jpg";} 
    else{revealCard()}
   
   function revealCard(){
   if (flipArray.length < 2){flipArray.push(numElFortyTwo); card42.src = cardSelect[numElFortyTwo - 1]}
   console.log(flipArray)
    }}}




function revealFortyThree(){
    if(tableArray.length > 51){
let numElFortyThree = tableArrayIndex[42]

if ( flipArray.includes(numElFortyThree)){ flipArray.pop(numElFortyThree); document.getElementById("card43").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFortyThree); card43.src = cardSelect[numElFortyThree - 1]}
console.log(flipArray)
 }}}




 function revealFortyFour(){
    if(tableArray.length > 51){
let numElFortyFour = tableArrayIndex[43]

if ( flipArray.includes(numElFortyFour)){ flipArray.pop(numElFortyFour); document.getElementById("card44").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFortyFour); card44.src = cardSelect[numElFortyFour - 1]}
console.log(flipArray)
 }}}




 function revealFortyFive(){
    if(tableArray.length > 51){
let numElFortyFive = tableArrayIndex[44]

if ( flipArray.includes(numElFortyFive)){ flipArray.pop(numElFortyFive); document.getElementById("card45").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFortyFive); card45.src = cardSelect[numElFortyFive - 1]}
console.log(flipArray)
 }}}



 function revealFortySix(){
    if(tableArray.length > 51){
let numElFortySix = tableArrayIndex[45]

if ( flipArray.includes(numElFortySix)){ flipArray.pop(numElFortySix); document.getElementById("card46").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFortySix); card46.src = cardSelect[numElFortySix - 1]}
console.log(flipArray)
 }}}



 function revealFortySeven(){
    if(tableArray.length > 51){
let numElFortySeven = tableArrayIndex[46]

if ( flipArray.includes(numElFortySeven)){ flipArray.pop(numElFortySeven); document.getElementById("card47").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFortySeven); card47.src = cardSelect[numElFortySeven - 1]}
console.log(flipArray)
 }}}



 function revealFortyEight(){
    if(tableArray.length > 51){
let numElFortyEight = tableArrayIndex[47]

if ( flipArray.includes(numElFortyEight)){ flipArray.pop(numElFortyEight); document.getElementById("card48").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFortyEight); card48.src = cardSelect[numElFortyEight - 1]}
console.log(flipArray)
 }}}



 function revealFortyNine(){
    if(tableArray.length > 51){
let numElFortyNine = tableArrayIndex[48]

if ( flipArray.includes(numElFortyNine)){ flipArray.pop(numElFortyNine); document.getElementById("card49").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFortyNine); card49.src = cardSelect[numElFortyNine- 1]}
console.log(flipArray)
 }}}



 function revealFifty(){
    if(tableArray.length > 51){
let numElFifty = tableArrayIndex[49]

if ( flipArray.includes(numElFifty)){ flipArray.pop(numElFifty); document.getElementById("card50").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFifty); card50.src = cardSelect[numElFifty - 1]}
console.log(flipArray)
 }}}



 function revealFiftyOne(){
    if(tableArray.length > 51){
let numElFiftyOne = tableArrayIndex[50]

if ( flipArray.includes(numElFiftyOne)){ flipArray.pop(numElFiftyOne); document.getElementById("card50").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFiftyOne); card50.src = cardSelect[numElFiftyOne - 1]}
console.log(flipArray)
 }}}



 function revealFiftyTwo(){
    if(tableArray.length > 51){
let numElFiftyTwo = tableArrayIndex[51]

if ( flipArray.includes(numElFiftyTwo)){ flipArray.pop(numElFiftyTwo); document.getElementById("card52").src="card back red.jpg";} 
 else{revealCard()}

function revealCard(){
if (flipArray.length < 2){flipArray.push(numElFiftyTwo); card52.src = cardSelect[numElFiftyTwo - 1]}
console.log(flipArray)
 }}}