




let cardSuitsArray = []; // available suits
let cardNumbersArray = []; // available card values
let randomSuitNum = "";// variable for generated suit index
let randomSuit = "";// variable for suit name
let randomCardNum = "";// variable for generated number
let chosenCard = "" // variable for generated number and suit combined - actual card
let tableArray = []; // cards dealt to table
let displayEl = document.getElementById('display');// cards display

// function for card generation
function pickCard(){

cardSuitsArray = ["c","d","h","s"] // all suits 
cardNumbersArray = [1,2,3,4,5,6,7,8,9,10,11,12,13] // all card values
randomSuitNum = Math.floor(Math.random()*cardSuitsArray.length)//suit generated by index
randomCardNum = Math.ceil(Math.random()*cardNumbersArray.length) // card value generated
randomSuit = cardSuitsArray[randomSuitNum]// suit name picked from generated index
chosenCard = randomCardNum + randomSuit // variable for value and suit of card


// condition to prevent duplicate card generation, if duplicate generated, re-run pickCard()
if(tableArray.includes(chosenCard)){pickCard();} 
else{
console.log(tableArray.includes(chosenCard))// this check should return false (for duplicates)
tableArray.push(chosenCard) // card pushed to table
displayEl.textContent = chosenCard + ","; // card displayed
}}


















